// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxxn7LJmQwhGYqoewnlUw95dTUgR6z3T0',
    appId: '1:878350871001:web:5e5e69491f5907d44bd1c8',
    messagingSenderId: '878350871001',
    projectId: 'traveland-d50a9',
    authDomain: 'traveland-d50a9.firebaseapp.com',
    storageBucket: 'traveland-d50a9.appspot.com',
    measurementId: 'G-RC2FY63N5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkd4-7kPXz7VPqd7TI7lBdaNxdSl77ceA',
    appId: '1:878350871001:android:ef6a588568bec82a4bd1c8',
    messagingSenderId: '878350871001',
    projectId: 'traveland-d50a9',
    storageBucket: 'traveland-d50a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIA8gyv1csOruVszF560x-snvrhlzF_tQ',
    appId: '1:878350871001:ios:50fcdc5ed34ba9c74bd1c8',
    messagingSenderId: '878350871001',
    projectId: 'traveland-d50a9',
    storageBucket: 'traveland-d50a9.appspot.com',
    iosClientId: '878350871001-1v8k7s56eu61e7iuboght34t9h8ag85l.apps.googleusercontent.com',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIA8gyv1csOruVszF560x-snvrhlzF_tQ',
    appId: '1:878350871001:ios:50fcdc5ed34ba9c74bd1c8',
    messagingSenderId: '878350871001',
    projectId: 'traveland-d50a9',
    storageBucket: 'traveland-d50a9.appspot.com',
    iosClientId: '878350871001-1v8k7s56eu61e7iuboght34t9h8ag85l.apps.googleusercontent.com',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxxn7LJmQwhGYqoewnlUw95dTUgR6z3T0',
    appId: '1:878350871001:web:b0d322d0cc62a9c34bd1c8',
    messagingSenderId: '878350871001',
    projectId: 'traveland-d50a9',
    authDomain: 'traveland-d50a9.firebaseapp.com',
    storageBucket: 'traveland-d50a9.appspot.com',
    measurementId: 'G-JYHM1N8VSN',
  );

}