// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBurjRK2yh02wWvbbKcYU3FMlXYkJdkdwY',
    appId: '1:18414324434:web:c4033c363b5b95130e3b0b',
    messagingSenderId: '18414324434',
    projectId: 'fasum-2a3e9',
    authDomain: 'fasum-2a3e9.firebaseapp.com',
    databaseURL: 'https://fasum-2a3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-2a3e9.appspot.com',
    measurementId: 'G-MMDPYG4FE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpt2cmzEkqDhfJU8rcJn2rLOxgM-dtrf0',
    appId: '1:18414324434:android:30c29181c5256f4c0e3b0b',
    messagingSenderId: '18414324434',
    projectId: 'fasum-2a3e9',
    databaseURL: 'https://fasum-2a3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-2a3e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ3VmTFf7fPHuIii634jKYCoVpJO-wvqg',
    appId: '1:18414324434:ios:a3f10a67b2b5d5630e3b0b',
    messagingSenderId: '18414324434',
    projectId: 'fasum-2a3e9',
    databaseURL: 'https://fasum-2a3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-2a3e9.appspot.com',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ3VmTFf7fPHuIii634jKYCoVpJO-wvqg',
    appId: '1:18414324434:ios:a307e5deb2012ff40e3b0b',
    messagingSenderId: '18414324434',
    projectId: 'fasum-2a3e9',
    databaseURL: 'https://fasum-2a3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-2a3e9.appspot.com',
    iosBundleId: 'com.example.projek.RunnerTests',
  );
}
